# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

score_seq <- function(tmp_seq, score_mat) {
    .Call('_universalmotif_score_seq', PACKAGE = 'universalmotif', tmp_seq, score_mat)
}

scan_1st_order <- function(sequence, score_mat, min_score) {
    .Call('_universalmotif_scan_1st_order', PACKAGE = 'universalmotif', sequence, score_mat, min_score)
}

DNA_to_int_di <- function(seqs) {
    .Call('_universalmotif_DNA_to_int_di', PACKAGE = 'universalmotif', seqs)
}

DNA_to_int_tri <- function(seqs) {
    .Call('_universalmotif_DNA_to_int_tri', PACKAGE = 'universalmotif', seqs)
}

scan_2nd_order <- function(sequence, score_mat, min_score) {
    .Call('_universalmotif_scan_2nd_order', PACKAGE = 'universalmotif', sequence, score_mat, min_score)
}

pcm_to_ppmC <- function(position, pseudocount = 0) {
    .Call('_universalmotif_pcm_to_ppmC', PACKAGE = 'universalmotif', position, pseudocount)
}

ppm_to_pcmC <- function(position, nsites = 0) {
    .Call('_universalmotif_ppm_to_pcmC', PACKAGE = 'universalmotif', position, nsites)
}

ppm_to_pwmC <- function(position, bkg = 0L, pseudocount = 0, nsites = 0) {
    .Call('_universalmotif_ppm_to_pwmC', PACKAGE = 'universalmotif', position, bkg, pseudocount, nsites)
}

pwm_to_ppmC <- function(position, bkg = 0L) {
    .Call('_universalmotif_pwm_to_ppmC', PACKAGE = 'universalmotif', position, bkg)
}

ppm_to_icmC <- function(position, bkg = 0L, relative_entropy = FALSE) {
    .Call('_universalmotif_ppm_to_icmC', PACKAGE = 'universalmotif', position, bkg, relative_entropy)
}

position_icscoreC <- function(position, bkg = 0L, type = "PPM", pseudocount = 0.8, nsites = 100, relative_entropy = FALSE) {
    .Call('_universalmotif_position_icscoreC', PACKAGE = 'universalmotif', position, bkg, type, pseudocount, nsites, relative_entropy)
}

icm_to_ppmC <- function(position) {
    .Call('_universalmotif_icm_to_ppmC', PACKAGE = 'universalmotif', position)
}

get_consensusC <- function(position, alphabet = "DNA", type = "PPM", pseudocount = 0.8) {
    .Call('_universalmotif_get_consensusC', PACKAGE = 'universalmotif', position, alphabet, type, pseudocount)
}

consensus_to_ppmC <- function(letter) {
    .Call('_universalmotif_consensus_to_ppmC', PACKAGE = 'universalmotif', letter)
}

consensus_to_ppmAAC <- function(letter) {
    .Call('_universalmotif_consensus_to_ppmAAC', PACKAGE = 'universalmotif', letter)
}

get_consensusAAC <- function(position, type = "PPM", pseudocount = 0) {
    .Call('_universalmotif_get_consensusAAC', PACKAGE = 'universalmotif', position, type, pseudocount)
}

