# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

single_to_k <- function(seq1, k) {
    .Call('_universalmotif_single_to_k', PACKAGE = 'universalmotif', seq1, k)
}

compare_motifs_cpp <- function(mots, index1, index2, method, minoverlap, RC, bkg, type, relative, minic, norm, nthreads) {
    .Call('_universalmotif_compare_motifs_cpp', PACKAGE = 'universalmotif', mots, index1, index2, method, minoverlap, RC, bkg, type, relative, minic, norm, nthreads)
}

compare_motifs_all_cpp <- function(mots, method, minoverlap, RC, bkg, type, relative, minic, norm, nthreads) {
    .Call('_universalmotif_compare_motifs_all_cpp', PACKAGE = 'universalmotif', mots, method, minoverlap, RC, bkg, type, relative, minic, norm, nthreads)
}

get_comparison_matrix <- function(ans, index1, index2, method, motnames) {
    .Call('_universalmotif_get_comparison_matrix', PACKAGE = 'universalmotif', ans, index1, index2, method, motnames)
}

peakfinder_cpp <- function(x, m = 3L) {
    .Call('_universalmotif_peakfinder_cpp', PACKAGE = 'universalmotif', x, m)
}

linbin_cpp <- function(x, gpoints) {
    .Call('_universalmotif_linbin_cpp', PACKAGE = 'universalmotif', x, gpoints)
}

motif_pvalue_cpp <- function(motifs, bkg, scores, k = 6L, nthreads = 1L) {
    .Call('_universalmotif_motif_pvalue_cpp', PACKAGE = 'universalmotif', motifs, bkg, scores, k, nthreads)
}

branch_and_bound_cpp_exposed <- function(mat, score) {
    .Call('_universalmotif_branch_and_bound_cpp_exposed', PACKAGE = 'universalmotif', mat, score)
}

expand_scores <- function(scores) {
    .Call('_universalmotif_expand_scores', PACKAGE = 'universalmotif', scores)
}

paths_alph_unsort <- function(paths, alph) {
    .Call('_universalmotif_paths_alph_unsort', PACKAGE = 'universalmotif', paths, alph)
}

paths_to_alph <- function(paths, alph) {
    .Call('_universalmotif_paths_to_alph', PACKAGE = 'universalmotif', paths, alph)
}

add_cols <- function(mot1, mot2, ic1, ic2, overlap) {
    .Call('_universalmotif_add_cols', PACKAGE = 'universalmotif', mot1, mot2, ic1, ic2, overlap)
}

motif_simil_internal <- function(mot1, mot2, method, min_overlap, tryRC, ic1, ic2, min_ic, norm) {
    .Call('_universalmotif_motif_simil_internal', PACKAGE = 'universalmotif', mot1, mot2, method, min_overlap, tryRC, ic1, ic2, min_ic, norm)
}

list_to_matrix_simil <- function(comparisons, mot_names, method) {
    .Call('_universalmotif_list_to_matrix_simil', PACKAGE = 'universalmotif', comparisons, mot_names, method)
}

merge_add_cols <- function(out) {
    .Call('_universalmotif_merge_add_cols', PACKAGE = 'universalmotif', out)
}

merge_motifs_get_offset <- function(mot1, mot2, method, min_overlap, ic1, ic2, min_ic, norm) {
    .Call('_universalmotif_merge_motifs_get_offset', PACKAGE = 'universalmotif', mot1, mot2, method, min_overlap, ic1, ic2, min_ic, norm)
}

merge_motifs_internal <- function(mot1, mot2, method, min_overlap, tryRC, ic1, ic2, min_ic, weight1, weight2, norm) {
    .Call('_universalmotif_merge_motifs_internal', PACKAGE = 'universalmotif', mot1, mot2, method, min_overlap, tryRC, ic1, ic2, min_ic, weight1, weight2, norm)
}

scan_sequences_cpp <- function(score_mats, seq_vecs, k, alph, min_scores, nthreads) {
    .Call('_universalmotif_scan_sequences_cpp', PACKAGE = 'universalmotif', score_mats, seq_vecs, k, alph, min_scores, nthreads)
}

shuffle_markov_cpp <- function(sequences, k, nthreads, seed) {
    .Call('_universalmotif_shuffle_markov_cpp', PACKAGE = 'universalmotif', sequences, k, nthreads, seed)
}

shuffle_euler_cpp <- function(sequences, k, nthreads, seed) {
    .Call('_universalmotif_shuffle_euler_cpp', PACKAGE = 'universalmotif', sequences, k, nthreads, seed)
}

shuffle_linear_cpp <- function(sequences, k, nthreads, seed) {
    .Call('_universalmotif_shuffle_linear_cpp', PACKAGE = 'universalmotif', sequences, k, nthreads, seed)
}

shuffle_k1_cpp <- function(sequences, nthreads, seed) {
    .Call('_universalmotif_shuffle_k1_cpp', PACKAGE = 'universalmotif', sequences, nthreads, seed)
}

count_klets_cpp <- function(sequences, k, nthreads) {
    .Call('_universalmotif_count_klets_cpp', PACKAGE = 'universalmotif', sequences, k, nthreads)
}

get_klets_cpp <- function(alph, k) {
    .Call('_universalmotif_get_klets_cpp', PACKAGE = 'universalmotif', alph, k)
}

shuffle_markov_loop <- function(seq_i_l, seq_i_r, k, seqout, lets, trans, trans_cols) {
    .Call('_universalmotif_shuffle_markov_loop', PACKAGE = 'universalmotif', seq_i_l, seq_i_r, k, seqout, lets, trans, trans_cols)
}

trim_motif_internal <- function(motif, ic_scores, min_ic) {
    .Call('_universalmotif_trim_motif_internal', PACKAGE = 'universalmotif', motif, ic_scores, min_ic)
}

universalmotif_cpp <- function(motif, name = "new motif", altname = NA_character_, family = NA_character_, organism = NA_character_, alphabet = "DNA", type = NA_character_, icscore = as.numeric( c()), nsites = as.numeric( c()), pseudocount = 1.0, bkg = as.numeric( c()), bkgsites = as.numeric( c()), consensus = NA_character_, strand = "+-", pval = as.numeric( c()), qval = as.numeric( c()), eval = as.numeric( c()), extrainfo = NA_character_) {
    .Call('_universalmotif_universalmotif_cpp', PACKAGE = 'universalmotif', motif, name, altname, family, organism, alphabet, type, icscore, nsites, pseudocount, bkg, bkgsites, consensus, strand, pval, qval, eval, extrainfo)
}

check_bkg_names <- function(alph, blet) {
    .Call('_universalmotif_check_bkg_names', PACKAGE = 'universalmotif', alph, blet)
}

validObject_universalmotif <- function(motif, throw_error = TRUE) {
    .Call('_universalmotif_validObject_universalmotif', PACKAGE = 'universalmotif', motif, throw_error)
}

summarise_motifs_cpp <- function(motifs) {
    .Call('_universalmotif_summarise_motifs_cpp', PACKAGE = 'universalmotif', motifs)
}

universalmotif_to_list <- function(motif) {
    .Call('_universalmotif_universalmotif_to_list', PACKAGE = 'universalmotif', motif)
}

comb2_cpp <- function(n) {
    .Call('_universalmotif_comb2_cpp', PACKAGE = 'universalmotif', n)
}

sort_unique_cpp <- function(x) {
    .Call('_universalmotif_sort_unique_cpp', PACKAGE = 'universalmotif', x)
}

table_cpp <- function(x) {
    .Call('_universalmotif_table_cpp', PACKAGE = 'universalmotif', x)
}

collapse_rows_mat <- function(seqs_k) {
    .Call('_universalmotif_collapse_rows_mat', PACKAGE = 'universalmotif', seqs_k)
}

collapse_cols_mat <- function(seqs_k) {
    .Call('_universalmotif_collapse_cols_mat', PACKAGE = 'universalmotif', seqs_k)
}

collapse_rows_df <- function(seqs_k) {
    .Call('_universalmotif_collapse_rows_df', PACKAGE = 'universalmotif', seqs_k)
}

collapse_cpp <- function(x) {
    .Call('_universalmotif_collapse_cpp', PACKAGE = 'universalmotif', x)
}

print_pb <- function(out) {
    invisible(.Call('_universalmotif_print_pb', PACKAGE = 'universalmotif', out))
}

update_pb <- function(i, max) {
    invisible(.Call('_universalmotif_update_pb', PACKAGE = 'universalmotif', i, max))
}

all_checks_collapse <- function(checks) {
    .Call('_universalmotif_all_checks_collapse', PACKAGE = 'universalmotif', checks)
}

pcm_to_ppmC <- function(position, pseudocount = 0) {
    .Call('_universalmotif_pcm_to_ppmC', PACKAGE = 'universalmotif', position, pseudocount)
}

ppm_to_pcmC <- function(position, nsites = 0) {
    .Call('_universalmotif_ppm_to_pcmC', PACKAGE = 'universalmotif', position, nsites)
}

ppm_to_pwmC <- function(position, bkg = 0L, pseudocount = 0, nsites = as.numeric( c())) {
    .Call('_universalmotif_ppm_to_pwmC', PACKAGE = 'universalmotif', position, bkg, pseudocount, nsites)
}

pwm_to_ppmC <- function(position, bkg = 0L) {
    .Call('_universalmotif_pwm_to_ppmC', PACKAGE = 'universalmotif', position, bkg)
}

ppm_to_icmC <- function(position, bkg = 0L, relative_entropy = FALSE) {
    .Call('_universalmotif_ppm_to_icmC', PACKAGE = 'universalmotif', position, bkg, relative_entropy)
}

position_icscoreC <- function(position, bkg = 0L, type = "PPM", pseudocount = 1, nsites = 100, relative_entropy = FALSE) {
    .Call('_universalmotif_position_icscoreC', PACKAGE = 'universalmotif', position, bkg, type, pseudocount, nsites, relative_entropy)
}

icm_to_ppmC <- function(position) {
    .Call('_universalmotif_icm_to_ppmC', PACKAGE = 'universalmotif', position)
}

get_consensusC <- function(pos, alphabet = "DNA", type = "PPM", pseudocount = 1) {
    .Call('_universalmotif_get_consensusC', PACKAGE = 'universalmotif', pos, alphabet, type, pseudocount)
}

consensus_to_ppmC <- function(letter) {
    .Call('_universalmotif_consensus_to_ppmC', PACKAGE = 'universalmotif', letter)
}

consensus_to_ppmAAC <- function(letter) {
    .Call('_universalmotif_consensus_to_ppmAAC', PACKAGE = 'universalmotif', letter)
}

get_consensusAAC <- function(position, type = "PPM", pseudocount = 0.0) {
    .Call('_universalmotif_get_consensusAAC', PACKAGE = 'universalmotif', position, type, pseudocount)
}

clean_up_check <- function(fails) {
    .Call('_universalmotif_clean_up_check', PACKAGE = 'universalmotif', fails)
}

check_fun_params <- function(param_args, param_len, param_null, expected_type) {
    .Call('_universalmotif_check_fun_params', PACKAGE = 'universalmotif', param_args, param_len, param_null, expected_type)
}

