# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

single_to_k <- function(seq1, k) {
    .Call('_universalmotif_single_to_k', PACKAGE = 'universalmotif', seq1, k)
}

peakfinder_cpp <- function(x, m = 3L) {
    .Call('_universalmotif_peakfinder_cpp', PACKAGE = 'universalmotif', x, m)
}

linbin_cpp <- function(x, gpoints) {
    .Call('_universalmotif_linbin_cpp', PACKAGE = 'universalmotif', x, gpoints)
}

calc_scores_cpp <- function(paths, score_mat) {
    .Call('_universalmotif_calc_scores_cpp', PACKAGE = 'universalmotif', paths, score_mat)
}

kmer_mat_to_probs_k1_cpp <- function(bb_mat, bkg, alph_sort) {
    .Call('_universalmotif_kmer_mat_to_probs_k1_cpp', PACKAGE = 'universalmotif', bb_mat, bkg, alph_sort)
}

init_paths_cpp <- function(score_mat, score, max_score) {
    .Call('_universalmotif_init_paths_cpp', PACKAGE = 'universalmotif', score_mat, score, max_score)
}

list_to_matrix <- function(paths) {
    .Call('_universalmotif_list_to_matrix', PACKAGE = 'universalmotif', paths)
}

calc_next_path_cpp <- function(score_mat, paths, score, max_score) {
    .Call('_universalmotif_calc_next_path_cpp', PACKAGE = 'universalmotif', score_mat, paths, score, max_score)
}

expand_scores <- function(scores) {
    .Call('_universalmotif_expand_scores', PACKAGE = 'universalmotif', scores)
}

paths_alph_unsort <- function(paths, alph) {
    .Call('_universalmotif_paths_alph_unsort', PACKAGE = 'universalmotif', paths, alph)
}

paths_to_alph <- function(paths, alph) {
    .Call('_universalmotif_paths_to_alph', PACKAGE = 'universalmotif', paths, alph)
}

add_cols <- function(mot1, mot2, ic1, ic2, overlap) {
    .Call('_universalmotif_add_cols', PACKAGE = 'universalmotif', mot1, mot2, ic1, ic2, overlap)
}

motif_simil_internal <- function(mot1, mot2, method, min_overlap, tryRC, ic1, ic2, min_ic, norm) {
    .Call('_universalmotif_motif_simil_internal', PACKAGE = 'universalmotif', mot1, mot2, method, min_overlap, tryRC, ic1, ic2, min_ic, norm)
}

list_to_matrix_simil <- function(comparisons, mot_names, method) {
    .Call('_universalmotif_list_to_matrix_simil', PACKAGE = 'universalmotif', comparisons, mot_names, method)
}

merge_add_cols <- function(out) {
    .Call('_universalmotif_merge_add_cols', PACKAGE = 'universalmotif', out)
}

merge_motifs_get_offset <- function(mot1, mot2, method, min_overlap, ic1, ic2, min_ic, norm) {
    .Call('_universalmotif_merge_motifs_get_offset', PACKAGE = 'universalmotif', mot1, mot2, method, min_overlap, ic1, ic2, min_ic, norm)
}

merge_motifs_internal <- function(mot1, mot2, method, min_overlap, tryRC, ic1, ic2, min_ic, weight1, weight2, norm) {
    .Call('_universalmotif_merge_motifs_internal', PACKAGE = 'universalmotif', mot1, mot2, method, min_overlap, tryRC, ic1, ic2, min_ic, weight1, weight2, norm)
}

numeric_to_integer_matrix <- function(mat) {
    .Call('_universalmotif_numeric_to_integer_matrix', PACKAGE = 'universalmotif', mat)
}

scan_seq_internal2 <- function(sequence, score_mat, min_score) {
    .Call('_universalmotif_scan_seq_internal2', PACKAGE = 'universalmotif', sequence, score_mat, min_score)
}

scan_seq_internal <- function(sequence, score_mat, min_score) {
    .Call('_universalmotif_scan_seq_internal', PACKAGE = 'universalmotif', sequence, score_mat, min_score)
}

LETTER_to_int <- function(seqs, k, letters) {
    .Call('_universalmotif_LETTER_to_int', PACKAGE = 'universalmotif', seqs, k, letters)
}

string_to_factor <- function(x, y) {
    .Call('_universalmotif_string_to_factor', PACKAGE = 'universalmotif', x, y)
}

res_to_index <- function(x) {
    .Call('_universalmotif_res_to_index', PACKAGE = 'universalmotif', x)
}

parse_k_res_helper_1 <- function(seqs, to_keep, mot_len, k) {
    .Call('_universalmotif_parse_k_res_helper_1', PACKAGE = 'universalmotif', seqs, to_keep, mot_len, k)
}

parse_k_res_helper_2 <- function(sequence, to_keep, mot_len) {
    .Call('_universalmotif_parse_k_res_helper_2', PACKAGE = 'universalmotif', sequence, to_keep, mot_len)
}

get_res_cpp <- function(to_keep, seqs_aschar, seq_ints, mot_lens, min_scores, max_scores, mot_names, seq_names, score_mats, strand, seq_lens, k) {
    .Call('_universalmotif_get_res_cpp', PACKAGE = 'universalmotif', to_keep, seqs_aschar, seq_ints, mot_lens, min_scores, max_scores, mot_names, seq_names, score_mats, strand, seq_lens, k)
}

res_list_to_df_cpp <- function(res) {
    .Call('_universalmotif_res_list_to_df_cpp', PACKAGE = 'universalmotif', res)
}

index_list_to_df_cpp <- function(to_keep, seq_names, lens_each) {
    .Call('_universalmotif_index_list_to_df_cpp', PACKAGE = 'universalmotif', to_keep, seq_names, lens_each)
}

shuffle_random_loop <- function(seqs_k_n, k, seqs_k_new_i, new_seq, seqs_k) {
    .Call('_universalmotif_shuffle_random_loop', PACKAGE = 'universalmotif', seqs_k_n, k, seqs_k_new_i, new_seq, seqs_k)
}

shuffle_markov_loop <- function(seq_i_l, seq_i_r, k, seqout, lets, trans, trans_cols) {
    .Call('_universalmotif_shuffle_markov_loop', PACKAGE = 'universalmotif', seq_i_l, seq_i_r, k, seqout, lets, trans, trans_cols)
}

eulerian_walk_cpp <- function(edgelist, firstl, seqlen, k, last, indices) {
    .Call('_universalmotif_eulerian_walk_cpp', PACKAGE = 'universalmotif', edgelist, firstl, seqlen, k, last, indices)
}

trim_motif_internal <- function(motif, ic_scores, min_ic) {
    .Call('_universalmotif_trim_motif_internal', PACKAGE = 'universalmotif', motif, ic_scores, min_ic)
}

universalmotif_cpp <- function(motif, name = "new motif", altname = NA_character_, family = NA_character_, organism = NA_character_, alphabet = "DNA", type = NA_character_, icscore = as.numeric( c()), nsites = as.numeric( c()), pseudocount = 1.0, bkg = as.numeric( c()), bkgsites = as.numeric( c()), consensus = NA_character_, strand = "+-", pval = as.numeric( c()), qval = as.numeric( c()), eval = as.numeric( c()), extrainfo = NA_character_) {
    .Call('_universalmotif_universalmotif_cpp', PACKAGE = 'universalmotif', motif, name, altname, family, organism, alphabet, type, icscore, nsites, pseudocount, bkg, bkgsites, consensus, strand, pval, qval, eval, extrainfo)
}

check_bkg_names <- function(alph, blet) {
    .Call('_universalmotif_check_bkg_names', PACKAGE = 'universalmotif', alph, blet)
}

validObject_universalmotif <- function(motif, throw_error = TRUE) {
    .Call('_universalmotif_validObject_universalmotif', PACKAGE = 'universalmotif', motif, throw_error)
}

summarise_motifs_cpp <- function(motifs) {
    .Call('_universalmotif_summarise_motifs_cpp', PACKAGE = 'universalmotif', motifs)
}

universalmotif_to_list <- function(motif) {
    .Call('_universalmotif_universalmotif_to_list', PACKAGE = 'universalmotif', motif)
}

table_cpp <- function(x) {
    .Call('_universalmotif_table_cpp', PACKAGE = 'universalmotif', x)
}

collapse_rows_mat <- function(seqs_k) {
    .Call('_universalmotif_collapse_rows_mat', PACKAGE = 'universalmotif', seqs_k)
}

collapse_cols_mat <- function(seqs_k) {
    .Call('_universalmotif_collapse_cols_mat', PACKAGE = 'universalmotif', seqs_k)
}

collapse_rows_df <- function(seqs_k) {
    .Call('_universalmotif_collapse_rows_df', PACKAGE = 'universalmotif', seqs_k)
}

#' @rdname utils-sequence
#' @export
get_klets <- function(lets, k) {
    .Call('_universalmotif_get_klets', PACKAGE = 'universalmotif', lets, k)
}

collapse_cpp <- function(x) {
    .Call('_universalmotif_collapse_cpp', PACKAGE = 'universalmotif', x)
}

print_pb <- function(out) {
    invisible(.Call('_universalmotif_print_pb', PACKAGE = 'universalmotif', out))
}

update_pb <- function(i, max) {
    invisible(.Call('_universalmotif_update_pb', PACKAGE = 'universalmotif', i, max))
}

all_checks_collapse <- function(checks) {
    .Call('_universalmotif_all_checks_collapse', PACKAGE = 'universalmotif', checks)
}

pcm_to_ppmC <- function(position, pseudocount = 0) {
    .Call('_universalmotif_pcm_to_ppmC', PACKAGE = 'universalmotif', position, pseudocount)
}

ppm_to_pcmC <- function(position, nsites = 0) {
    .Call('_universalmotif_ppm_to_pcmC', PACKAGE = 'universalmotif', position, nsites)
}

ppm_to_pwmC <- function(position, bkg = 0L, pseudocount = 0, nsites = as.numeric( c())) {
    .Call('_universalmotif_ppm_to_pwmC', PACKAGE = 'universalmotif', position, bkg, pseudocount, nsites)
}

pwm_to_ppmC <- function(position, bkg = 0L) {
    .Call('_universalmotif_pwm_to_ppmC', PACKAGE = 'universalmotif', position, bkg)
}

ppm_to_icmC <- function(position, bkg = 0L, relative_entropy = FALSE) {
    .Call('_universalmotif_ppm_to_icmC', PACKAGE = 'universalmotif', position, bkg, relative_entropy)
}

position_icscoreC <- function(position, bkg = 0L, type = "PPM", pseudocount = 1, nsites = 100, relative_entropy = FALSE) {
    .Call('_universalmotif_position_icscoreC', PACKAGE = 'universalmotif', position, bkg, type, pseudocount, nsites, relative_entropy)
}

icm_to_ppmC <- function(position) {
    .Call('_universalmotif_icm_to_ppmC', PACKAGE = 'universalmotif', position)
}

get_consensusC <- function(pos, alphabet = "DNA", type = "PPM", pseudocount = 1) {
    .Call('_universalmotif_get_consensusC', PACKAGE = 'universalmotif', pos, alphabet, type, pseudocount)
}

consensus_to_ppmC <- function(letter) {
    .Call('_universalmotif_consensus_to_ppmC', PACKAGE = 'universalmotif', letter)
}

consensus_to_ppmAAC <- function(letter) {
    .Call('_universalmotif_consensus_to_ppmAAC', PACKAGE = 'universalmotif', letter)
}

get_consensusAAC <- function(position, type = "PPM", pseudocount = 0.0) {
    .Call('_universalmotif_get_consensusAAC', PACKAGE = 'universalmotif', position, type, pseudocount)
}

clean_up_check <- function(fails) {
    .Call('_universalmotif_clean_up_check', PACKAGE = 'universalmotif', fails)
}

check_fun_params <- function(param_args, param_len, param_null, expected_type) {
    .Call('_universalmotif_check_fun_params', PACKAGE = 'universalmotif', param_args, param_len, param_null, expected_type)
}

